export const data = [
    {   
        id:1,
        book_name:"Think and Grow Rich",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.5",
        img:"https://rukminim1.flixcart.com/image/416/416/kf5pzm80/book/8/8/4/think-and-grow-rich-original-imafvztnm7kzdzz9.jpeg?q=70",
        price:"₹ 115",
        discount:"48%",
    },
    {   
        id:2,
        book_name:"You Only Live Once",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.5",
        img:"https://rukminim1.flixcart.com/image/612/612/kjrh2fk0/book/6/w/u/you-only-live-once-original-imafz9geb8hptuth.jpeg?q=70",
        price:"₹ 200",
        discount:"32%",
    },
    {   
        id:3,
        book_name:"Quantitative aptitude for competitive",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.2",
        img:"https://rukminim1.flixcart.com/image/612/612/kirr24w0-0/book/a/h/u/quantitative-aptitude-for-competitive-examinations-original-imafyhj2hrcgam9k.jpeg?q=70",
        price:"₹ 235",
        discount:"50%",
    },
    {   
        id:4,
        book_name:"Indian Polity",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.0",
        img:"https://rukminim1.flixcart.com/image/612/612/kn7sdjk0/book/p/k/o/indian-polity-6-edition-e-original-imagfy6fgxhjbge2.jpeg?q=70",
        price:"₹ 340",
        discount:"64%",
    },
    {   
        id:5,
        book_name:"SSC Multi Tasking Non-Technical Guide 2021",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.6",
        img:"https://rukminim1.flixcart.com/image/612/612/kkzrpu80/book/c/q/z/ssc-multi-tasking-non-technical-guide-2021-hindi-original-imagy7xayh8m6hsv.jpeg?q=70",
        price:"₹ 395",
        discount:"20%",
    },
    {   
        id:6,
        book_name:"Think Like  a Monk",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.9",
        img:"https://rukminim1.flixcart.com/image/612/612/khtghow0-0/book/1/9/o/think-like-a-monk-original-imafxr36mwua29uj.jpeg?q=70",
        price:"₹ 420",
        discount:"10%",
    },
    {   
        id:7,
        book_name:"One Arranged Murder",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.3",
        img:"https://rukminim1.flixcart.com/image/612/612/kdxfc7k0/book/1/3/9/one-arranged-murder-original-imafuqfpfthrvzsz.jpeg?q=70",
        price:"₹ 676",
        discount:"55%",
    },
    {   
        id:8,
        book_name:"151 Eassays for IAS/Pcs & other Competitive Exams",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.5",
        img:"https://rukminim1.flixcart.com/image/612/612/k687wy80/book/1/8/7/151-essays-for-ias-pcs-other-competitive-exams-3rd-edition-original-imafzqkumwvgggnj.jpeg?q=70",
        price:"₹ 323",
        discount:"31%",
    },
    {   
        id:9,
        book_name:"Objective",
        subtitle:"English,Paperback,Hill Napoleon",
        star:"4.5",
        img:"https://rukminim1.flixcart.com/image/612/612/kcuug7k0/book/2/5/5/objective-ncert-at-your-fingertips-original-imaftvmesyeghnq4.jpeg?q=70",
        price:"₹ 400",
        discount:"33%",
    }
]